### ISSUE TITLE
how to use it , i have installed this app ,but i can not find any changes when open it .

### ISSUE THREAD

**Issue by mituaierlan** [duoluo9/ProjectionScreenPlayer#1]

**Comment by DL-ZhangTeng** [comment]
不好意思，这么长时间才回复。
首先准备在同一局域网下的2部安卓设备，分别运行ProjectionScreenPlayer和https://github.com/duoluo9/ProjectionScreenSender，在Sender端输入Player端的ip地址即可，运行Sender端的设备必须是Android5.0+
